Ci/create GitHub actions flow
shauliz/node-express-multitenant pull request #7
Opened 2022-01-29 20:03 UTC by yakirgot

2022-01-29 20:58 UTC, shauliz requested changes

2022-01-29 20:58 UTC, shauliz commented on src/app/express-middleware.ts
> +    const data = { accountId: accountIdExtractor(request) };
@yakirgot the express js convention is req, res. Please change back.

2022-01-30 05:51 UTC, shauliz approved these changes

2022-01-30 18:42 UTC, shauliz approved these changes

2022-01-30 19:17 UTC, yakirgot commented on package.json
> +    "test": "npx prisma migrate dev && jest",
shouldn't it be in postinstall?

2022-01-30 19:55 UTC, shauliz approved these changes

2022-01-30 19:57 UTC, merged